// Kamus bilingual PDC (gelombang-1: shell). Pilihan persisten di
// localStorage (pola lib/tema.ts). Default Indonesia. Fallback: bila kunci
// hilang di bahasa aktif, pakai teks Indonesia agar tak ada blank.
// Halaman + pesan API menyusul gelombang berikut (tetap Indonesia dulu).
export type Lang = "id" | "en";

export const KUNCI_BAHASA = "pdc-bahasa";

export function bacaBahasa(): Lang {
  if (typeof window === "undefined") return "id";
  return window.localStorage.getItem(KUNCI_BAHASA) === "en" ? "en" : "id";
}

export function simpanBahasa(l: Lang) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(KUNCI_BAHASA, l);
  } catch {
    // localStorage penuh/diblokir: pilihan sesi ini saja.
  }
}

const KAMUS = {
  "nav.dashboard": { id: "Dashboard", en: "Dashboard" },
  "nav.proyek": { id: "Proyek", en: "Projects" },
  "nav.sesi": { id: "Sesi", en: "Sessions" },
  "nav.status": { id: "Status", en: "Status" },
  "nav.riwayat": { id: "Riwayat", en: "History" },
  "nav.statistik": { id: "Statistik", en: "Statistics" },
  "nav.notifikasi": { id: "Notifikasi", en: "Notifications" },
  "nav.pengaturan": { id: "Pengaturan", en: "Settings" },
  "shell.menu": { id: "Menu", en: "Menu" },
  "menu.navigasi": { id: "Menu navigasi", en: "Navigation menu" },
  "shell.muatSesi": { id: "Memuat sesi…", en: "Loading session…" },
  "shell.ciutkan": { id: "Ciutkan sidebar", en: "Collapse sidebar" },
  "shell.bentangkan": { id: "Bentangkan sidebar", en: "Expand sidebar" },
  "user.masukGithub": { id: "Login GitHub", en: "GitHub Login" },
  "user.masukDenganGithub": { id: "Masuk dengan GitHub", en: "Sign in with GitHub" },
  "user.keluar": { id: "Keluar", en: "Log out" },
  "user.tanyaKeluar": { id: "Keluar dari PDC?", en: "Log out of PDC?" },
  "user.pesanKeluar": {
    id: "Sesi GitHub-mu di perangkat ini diakhiri. Antrian dan data di database tetap aman.",
    en: "Your GitHub session on this device will end. Queue and database data stay safe.",
  },
  "user.yaKeluar": { id: "Ya, keluar", en: "Yes, log out" },
  "user.pengaturan": { id: "Pengaturan", en: "Settings" },
  "user.menuPengguna": { id: "Menu pengguna", en: "User menu" },
  "user.terhubung": { id: "Connected", en: "Connected" },
  "search.placeholder": { id: "Cari proyek, tugas, atau log…", en: "Search projects, tasks, or logs…" },
  "search.proyek": { id: "Proyek", en: "Project" },
  "search.tugas": { id: "Tugas", en: "Task" },
  "search.perintah": { id: "Perintah", en: "Command" },
  "modal.batal": { id: "Batal", en: "Cancel" },
  "modal.tutup": { id: "Tutup", en: "Close" },
  "modal.yaLanjut": { id: "Ya, lanjutkan", en: "Yes, continue" },
  "landing.sambut": { id: "Selamat Datang Kembali", en: "Welcome Back" },
  "landing.sub": {
    id: "Agar tetap terhubung, masuk dengan akun GitHub-mu untuk membuka command center AI.",
    en: "To stay connected, sign in with your GitHub account to open the AI command center.",
  },
  "landing.catatan": { id: "Baca repo · merge PR hanya atas persetujuanmu.", en: "Read repos · merge PRs only with your approval." },
  "landing.fitur1j": { id: "Pantau AI live", en: "Monitor AI live" },
  "landing.fitur1d": {
    id: "Status, progress, dan activity semua repo dalam satu layar.",
    en: "Status, progress, and activity of all repos on one screen.",
  },
  "landing.fitur2j": { id: "Kelola antrian", en: "Manage queue" },
  "landing.fitur2d": {
    id: "Kirim perintah, hentikan kerja, lihat riwayat per proyek.",
    en: "Send commands, stop work, view history per project.",
  },
  "landing.fitur3j": { id: "Terhubung GitHub", en: "Connected to GitHub" },
  "landing.fitur3d": { id: "Repo live + jembatan MCP ke OpenCode.", en: "Live repos + MCP bridge to OpenCode." },
  "gate.judul": { id: "Selamat datang di Project Develop Center", en: "Welcome to Project Develop Center" },
  "gate.sub": {
    id: "Sambungkan akun GitHub untuk melihat semua repositori yang kamu pantau dalam satu dashboard.",
    en: "Connect your GitHub account to see all monitored repositories in one dashboard.",
  },
  "gate.cta": { id: "Sambungkan Akun GitHub", en: "Connect GitHub Account" },
  "bahasa.label": { id: "Bahasa", en: "Language" },
  "dash.proyekAktif": { id: "Proyek Aktif", en: "Active Projects" },
  "dash.aiBekerja": { id: "AI Bekerja", en: "AI Working" },
  "dash.tugasSelesai": { id: "Tugas Selesai", en: "Tasks Done" },
  "dash.sedangAktif": { id: "Sedang Aktif", en: "Currently Active" },
  "dash.butuhPerhatian": { id: "Perlu Perhatian", en: "Needs Attention" },
  "dash.kosongSesi": { id: "Tidak ada sesi AI aktif di repo mana pun.", en: "No active AI sessions in any repo." },
  "dash.kosongTenang": {
    id: "Semua tenang — tidak ada AI yang bekerja. Kirim perintah dari menu Proyek.",
    en: "All quiet — no AI working. Send a command from the Projects menu.",
  },
  "dash.gagalRepo": { id: "Gagal memuat repo GitHub — menampilkan data contoh.", en: "Failed to load GitHub repos — showing sample data." },
  "dash.muatRepo": { id: "Memuat repo GitHub…", en: "Loading GitHub repos…" },
  "kartu.aiBekerja": { id: "AI bekerja", en: "AI working" },
  "kartu.aiAktif": { id: "AI aktif", en: "AI active" },
  "kartu.titleBekerja": { id: "AI sedang menyunting kode di repo ini", en: "AI is editing code in this repo" },
  "kartu.titleAktif": { id: "Sesi AI aktif di repo ini", en: "Active AI session in this repo" },
  "kartu.jadikanPublic": { id: "Jadikan public", en: "Make public" },
  "kartu.jadikanPrivate": { id: "Jadikan private", en: "Make private" },
  "kartu.perintah": { id: "Perintah", en: "Command" },
  "kartu.stop": { id: "Stop", en: "Stop" },
  "antre.perintahDiAntre": { id: "perintah dalam antrian", en: "commands in queue" },
  "notif.judul": { id: "Notifikasi", en: "Notifications" },
  "notif.baru": { id: "baru", en: "new" },
  "notif.sub": {
    id: "PR, error, dan penyelesaian AI 24 jam terakhir dari semua proyek.",
    en: "PRs, errors, and AI completions in the last 24 hours across all projects.",
  },
  "notif.tandaiSemua": { id: "Tandai semua dibaca", en: "Mark all as read" },
  "notif.kosongJudul": { id: "Tidak ada notifikasi", en: "No notifications" },
  "notif.kosongSub": {
    id: "Semua tenang. PR baru dan error AI akan muncul di sini.",
    en: "All quiet. New PRs and AI errors will appear here.",
  },
  "notif.tandai": { id: "Tandai dibaca", en: "Mark as read" },
  "notif.muat": { id: "Memuat…", en: "Loading…" },
  "notif.dtkLalu": { id: "dtk lalu", en: "s ago" },
  "notif.mntLalu": { id: "mnt lalu", en: "m ago" },
  "notif.jamLalu": { id: "jam lalu", en: "h ago" },
  "stat.judul": { id: "Statistik GitHub", en: "GitHub Statistics" },
  "stat.subKosong": { id: "Streak, kontribusi, dan bahasa setahun terakhir.", en: "Streak, contributions, and languages from the past year." },
  "stat.subAkun": { id: "Akun {login} · setahun terakhir", en: "Account {login} · past year" },
  "stat.total": { id: "Total Kontribusi", en: "Total Contributions" },
  "stat.kini": { id: "Streak Kini (hari)", en: "Current Streak (days)" },
  "stat.belumMulai": { id: "belum mulai", en: "not started" },
  "stat.terpanjang": { id: "Streak Terpanjang", en: "Longest Streak" },
  "stat.bintang": { id: "Bintang", en: "Stars" },
  "stat.commit": { id: "Commit", en: "Commits" },
  "stat.pr": { id: "Pull Request", en: "Pull Requests" },
  "stat.issue": { id: "Issue", en: "Issues" },
  "stat.bahasa": { id: "Bahasa Teratas", en: "Top Languages" },
  "stat.bahasaKosong": { id: "Belum ada data bahasa.", en: "No language data yet." },
  "stat.gagalJudul": { id: "Gagal memuat statistik", en: "Failed to load statistics" },
  "stat.gagalSub": {
    id: "GitHub tidak menjawab atau token kedaluwarsa. Coba lagi atau login ulang.",
    en: "GitHub did not respond or the token expired. Try again or log in again.",
  },
  "stat.cobaLagi": { id: "Coba lagi", en: "Try again" },
  "stat.muat": { id: "Memuat…", en: "Loading…" },
  "riw.judul": { id: "Riwayat", en: "History" },
  "riw.filterProyek": { id: "Filter proyek", en: "Filter projects" },
  "riw.semuaProyek": { id: "Semua proyek", en: "All projects" },
  "riw.tugas": { id: "Tugas", en: "Tasks" },
  "riw.perintah": { id: "Perintah", en: "Commands" },
  "riw.kolTugas": { id: "Tugas", en: "Task" },
  "riw.kolProyek": { id: "Proyek", en: "Project" },
  "riw.kolStatus": { id: "Status", en: "Status" },
  "riw.kolProgress": { id: "Progress", en: "Progress" },
  "riw.kosongTugas": { id: "Belum ada tugas.", en: "No tasks yet." },
  "riw.kosongPerintah": { id: "Belum ada perintah.", en: "No commands yet." },
  "pro.hasilCari": { id: "Hasil Pencarian ({n})", en: "Search Results ({n})" },
  "pro.judulProyek": { id: "Proyek ({n})", en: "Projects ({n})" },
  "pro.kosongCari": { id: 'Tidak ada proyek yang cocok dengan "{q}".', en: 'No projects matching "{q}".' },
  "pro.kosongUmum": { id: "Belum ada proyek.", en: "No projects yet." },
  "pro.sync": { id: "Sync GitHub", en: "Sync GitHub" },
  "pro.muatProyek": { id: "Memuat proyek…", en: "Loading project…" },
  "pro.kembaliProyek": { id: "← Kembali ke Proyek", en: "← Back to Projects" },
  "pro.tugasLabel": { id: "Tugas: ", en: "Task: " },
  "pro.tidakAdaTask": { id: "Tidak ada task aktif. Kirim perintah untuk memulai.", en: "No active tasks. Send a command to start." },
  "pro.tabAktivitas": { id: "Aktivitas", en: "Activity" },
  "pro.tabRingkasan": { id: "Ringkasan", en: "Summary" },
  "pro.kosongFeed": { id: "Belum ada aktivitas.", en: "No activity yet." },
  "pro.kosongSesiPlugin": {
    id: "Belum ada sesi tercatat. Pasang plugin pdc-presence di repo ini agar sesi OpenCode terlacak otomatis.",
    en: "No sessions recorded. Install the pdc-presence plugin in this repo to track OpenCode sessions automatically.",
  },
  "pro.kosongSesi": { id: "Belum ada sesi tercatat.", en: "No sessions recorded." },
  "pro.kosongRingkasan": {
    id: "Belum ada ringkasan. Ringkasan ditulis di akhir tiap giliran jawaban agent.",
    en: "No summaries yet. Summaries are written at the end of each agent turn.",
  },
  "pro.tanpaRingkasan": { id: "tanpa ringkasan", en: "no summary" },
  "pro.terakhirLabel": { id: "Terakhir: ", en: "Latest: " },
  "pro.komitLabel": { id: "komit ", en: "commit " },
  "pro.mulaiLabel": { id: "mulai ", en: "started " },
  "pro.stopJudul": { id: "Hentikan kerja AI?", en: "Stop AI work?" },
  "pro.stopPesan": {
    id: "Kerja AI di {repo} dihentikan. Perintah pending dibatalkan dan task ditandai gagal.",
    en: "AI work in {repo} will be stopped. Pending commands are cancelled and tasks marked failed.",
  },
  "pro.stopPesanDetail": {
    id: "Kerja AI di {repo} dihentikan. Perintah pending dibatalkan.",
    en: "AI work in {repo} will be stopped. Pending commands are cancelled.",
  },
  "pro.stopYa": { id: "Ya, hentikan", en: "Yes, stop it" },
  "pro.visJudul": { id: "Ubah visibilitas repo?", en: "Change repo visibility?" },
  "pro.visPesanPublic": {
    id: "{repo} jadi PUBLIC: semua orang bisa lihat + Pages aktif.",
    en: "{repo} becomes PUBLIC: everyone can see it + Pages active.",
  },
  "pro.visPesanPrivate": {
    id: "{repo} jadi PRIVATE: hanya kamu + kolaborator yang bisa lihat.",
    en: "{repo} becomes PRIVATE: only you + collaborators can see it.",
  },
  "pro.visYa": { id: "Ya, ubah", en: "Yes, change it" },
  "pro.hapusJudul": { id: "Hapus sesi ini?", en: "Delete this session?" },
  "pro.hapusPesanErr": { id: "Gagal menghapus (server menolak). Coba lagi.", en: "Delete failed (server refused). Try again." },
  "pro.hapusPesan": {
    id: "Sesi {id}… dihapus dari daftar (jejak file ikut terhapus; feed riwayat tetap).",
    en: "Session {id}… removed from the list (file traces deleted too; history feed kept).",
  },
  "pro.hapusYa": { id: "Ya, hapus", en: "Yes, delete it" },
  "sesi.judul": { id: "Sesi AI", en: "AI Sessions" },
  "sesi.sub": { id: "Semua sesi OpenCode lintas repo. Baris feed riwayat tidak ikut terhapus.", en: "All OpenCode sessions across repos. History feed rows are kept." },
  "sesi.filterAktif": { id: "Aktif ({n})", en: "Active ({n})" },
  "sesi.filterSemua": { id: "Semua ({n})", en: "All ({n})" },
  "sesi.kosongAktif": { id: "Tidak ada sesi AI aktif di repo mana pun.", en: "No active AI sessions in any repo." },
  "sesi.kosongSemua": { id: "Belum ada sesi tercatat.", en: "No sessions recorded." },
  "sesi.tanpaProyek": { id: "tanpa proyek", en: "no project" },
  "sesi.selesai": { id: "Selesai", en: "Done" },
  "sesi.nonaktif": { id: "Nonaktif", en: "Inactive" },
  "sesi.aktif": { id: "Aktif", en: "Active" },
  "sesi.bekerja": { id: "Bekerja", en: "Working" },
  "sesi.siagaHening": { id: "Siaga · hening {n} mnt", en: "Idle · quiet {n} min" },
  "sesi.hapusSesi": { id: "Hapus sesi", en: "Delete session" },
  "status.judul": { id: "Status", en: "Status" },
  "status.sub": {
    id: "Observasi read-only: deploy, bridge, database, plugin. Tanpa tombol aksi.",
    en: "Read-only observability: deploy, bridge, database, plugins. No action buttons.",
  },
  "status.gagal": { id: "Gagal memuat status. Coba lagi.", en: "Failed to load status. Try again." },
  "status.deployJudul": { id: "Deploy Production", en: "Production Deploy" },
  "status.deployKosong": { id: "Tidak tersedia.", en: "Unavailable." },
  "status.bridgeJudul": { id: "Bridge MCP", en: "MCP Bridge" },
  "status.hidup": { id: "Hidup", en: "Up" },
  "status.mati": { id: "Mati", en: "Down" },
  "status.dbJudul": { id: "Database", en: "Database" },
  "status.pluginJudul": { id: "Plugin per Repo (terkini {v})", en: "Per-Repo Plugins (latest {v})" },
  "status.pluginKosong": { id: "Belum ada proyek terdaftar.", en: "No registered projects." },
  "status.tanpaVersi": { id: "tanpa versi", en: "no version" },
  "status.belumPernah": { id: "Belum pernah", en: "Never" },
  "status.basi": { id: "Basi", en: "Stale" },
  "status.terkini": { id: "Terkini", en: "Current" },
  "status.belumPernahWaktu": { id: "belum pernah", en: "never" },
  "cmd.judul": { id: "Kirim Perintah ke AI", en: "Send Command to AI" },
  "cmd.pilihProyek": { id: "Pilih Proyek", en: "Select Project" },
  "cmd.instruksi": { id: "Instruksi", en: "Instructions" },
  "cmd.contoh": { id: "Contoh: Tambahkan fitur lupa password di halaman login", en: "Example: Add a forgot-password feature to the login page" },
  "cmd.gagal": { id: "Gagal menyimpan ke database. Coba lagi.", en: "Failed to save to the database. Try again." },
  "cmd.kirim": { id: "Kirim", en: "Send" },
  "antre.judul": { id: "Antrian Perintah", en: "Command Queue" },
  "antre.server": { id: "Server", en: "Server" },
  "antre.serverTitle": {
    id: "Tersimpan di server, terbawa antar perangkat",
    en: "Stored on the server, synced across devices",
  },
  "antre.lokal": { id: "Lokal", en: "Local" },
  "antre.lokalTitle": { id: "Mode lokal: tersimpan di browser ini saja", en: "Local mode: stored in this browser only" },
  "antre.bersihkan": { id: "Bersihkan selesai", en: "Clear finished" },
  "antre.gagalHapus": { id: "Gagal membersihkan. Coba lagi.", en: "Failed to clear. Try again." },
  "antre.lokalWarn": {
    id: "Mode lokal — perintah hanya di browser ini. Login untuk memindah ke server.",
    en: "Local mode — commands stay in this browser. Log in to move them to the server.",
  },
  "antre.migrasi": { id: "{n} perintah lokal dipindah ke server.", en: "{n} local commands moved to the server." },
  "antre.kosongA": { id: "Belum ada perintah. Klik", en: "No commands yet. Click" },
  "antre.kosongB": { id: "pada kartu proyek untuk mengirim satu.", en: "on a project card to send one." },
  "antre.labelPending": { id: "Menunggu", en: "Pending" },
  "antre.labelProcessing": { id: "Diproses", en: "Processing" },
  "antre.labelCompleted": { id: "Selesai", en: "Done" },
  "antre.labelFailed": { id: "Gagal", en: "Failed" },
  "feed.judul": { id: "Activity Feed", en: "Activity Feed" },
  "feed.kosong": { id: "Belum ada aktivitas. Kirim perintah untuk memulai.", en: "No activity yet. Send a command to start." },
  "feed.di": { id: "di", en: "in" },
  "pr.judul": { id: "PR Terbuka", en: "Open PRs" },
  "pr.aria": { id: "PR terbuka {repo}", en: "Open PRs {repo}" },
  "pr.gagalMuat": { id: "Gagal memuat PR. Coba lagi.", en: "Failed to load PRs. Try again." },
  "pr.mergeGagal": { id: "Merge gagal.", en: "Merge failed." },
  "pr.jaringanGagal": { id: "Jaringan gagal. Coba lagi.", en: "Network failed. Try again." },
  "pr.muat": { id: "Memuat PR…", en: "Loading PRs…" },
  "pr.kosong": { id: "Tidak ada PR terbuka.", en: "No open PRs." },
  "pr.mergeBtn": { id: "Merge", en: "Merge" },
  "pr.mergeJudul": { id: "Merge PR #{n}?", en: "Merge PR #{n}?" },
  "pr.mergePesan": {
    id: 'PR "{title}" dari branch {branch} digabung dengan merge commit. Tindakan ini tidak bisa dibatalkan.',
    en: 'PR "{title}" from branch {branch} will be merged with a merge commit. This cannot be undone.',
  },
  "pr.merging": { id: "Menggabungkan…", en: "Merging…" },
  "pr.mergeYa": { id: "Ya, merge", en: "Yes, merge it" },
  "atur.judul": { id: "Pengaturan", en: "Settings" },
  "atur.sub": { id: "Kelola preferensi, kredensial integrasi, dan keamanan proyek Anda.", en: "Manage preferences, integration credentials, and project security." },
  "atur.profilJudul": { id: "Profil & Tampilan", en: "Profile & Appearance" },
  "atur.penggunaDefault": { id: "Pengguna", en: "User" },
  "atur.emailKosong": { id: "Email tidak tersedia", en: "Email unavailable" },
  "atur.providerJudul": { id: "Provider LLM (BYOK)", en: "LLM Providers (BYOK)" },
  "atur.providerSub": {
    id: "Simpan API key untuk mengaktifkan asisten AI eksternal. Kredensial akan dienkripsi.",
    en: "Save API keys to enable external AI assistants. Credentials are encrypted.",
  },
  "atur.tersimpan": { id: "{p} tersimpan ✓", en: "{p} saved ✓" },
  "atur.simpanBtn": { id: "Simpan", en: "Save" },
  "atur.simpanJudul": { id: "Simpan API Key {label}", en: "Save {label} API Key" },
  "atur.simpanPesan": {
    id: "API Key untuk {label} akan dienkripsi di server (BYOK) dan tidak diekspos ke antarmuka. Lanjutkan?",
    en: "The {label} API key will be encrypted server-side (BYOK) and never exposed to the UI. Continue?",
  },
  "atur.simpanYa": { id: "Simpan Key", en: "Save Key" },
  "atur.gagalSimpan": { id: "Gagal menyimpan.", en: "Failed to save." },
  "atur.githubJudul": { id: "Integrasi GitHub", en: "GitHub Integration" },
  "atur.githubSub": {
    id: "Simpan Personal Access Token (PAT) untuk keperluan CI/CD dan PR. Token dijamin aman.",
    en: "Save a Personal Access Token (PAT) for CI/CD and PRs. Tokens are kept safe.",
  },
  "atur.mcpJudul": { id: "Jembatan MCP (OpenCode)", en: "MCP Bridge (OpenCode)" },
  "atur.mcpSub": { id: "API key untuk mengizinkan akses ke endpoint MCP. Key hanya tampil sekali.", en: "API keys granting access to MCP endpoints. Keys are shown only once." },
  "atur.namaPlaceholder": { id: "Nama key, mis. opencode-local", en: "Key name, e.g. opencode-local" },
  "atur.buatKey": { id: "Buat Key", en: "Create Key" },
  "atur.salinJudul": { id: "Salin sekarang — tidak ditampilkan lagi:", en: "Copy now — it won't be shown again:" },
  "atur.tersalin": { id: "Tersalin", en: "Copied" },
  "atur.salin": { id: "Salin", en: "Copy" },
  "atur.keyAktif": { id: "Key aktif ({n})", en: "Active keys ({n})" },
  "atur.belumKey": { id: "Belum ada key.", en: "No keys yet." },
  "atur.dicabut": { id: "dicabut", en: "revoked" },
  "atur.dipakai": { id: "dipakai {t}", en: "used {t}" },
  "atur.belumDipakai": { id: "belum dipakai", en: "never used" },
  "atur.cabutTitle": { id: "Cabut key", en: "Revoke key" },
  "atur.cabutJudul": { id: "Cabut Key?", en: "Revoke Key?" },
  "atur.cabutPesan": { id: "Yakin ingin mencabut akses untuk key '{name}'?", en: "Revoke access for key '{name}'?" },
  "atur.hapusTitle": { id: "Hapus permanen", en: "Delete permanently" },
  "atur.hapusJudul": { id: "Hapus Permanen?", en: "Delete Permanently?" },
  "atur.hapusPesan": {
    id: "Key '{name}' yang sudah dicabut akan dihapus dari daftar dan tidak bisa dikembalikan.",
    en: "Revoked key '{name}' will be permanently removed from the list.",
  },
  "atur.hapusYa": { id: "Ya, hapus", en: "Yes, delete it" },
  "atur.bersihJudul": { id: "Bersihkan Key yang Dicabut", en: "Clean Up Revoked Keys" },
  "atur.bersihSub": { id: "Menghapus permanen semua key yang sudah dicabut dari daftar.", en: "Permanently remove all revoked keys from the list." },
  "atur.bersihJudulModal": { id: "Bersihkan Key Dicabut?", en: "Clean Up Revoked Keys?" },
  "atur.bersihPesan": {
    id: "Semua key yang sudah dicabut akan dihapus permanen dari daftar. Key aktif tidak tersentuh.",
    en: "All revoked keys will be permanently removed. Active keys are untouched.",
  },
  "atur.bersihYa": { id: "Ya, bersihkan", en: "Yes, clean up" },
  "atur.bersihBtn": { id: "Bersihkan", en: "Clean up" },
  "atur.cabutSemuaJudul": { id: "Cabut Semua API Key Aktif", en: "Revoke All Active API Keys" },
  "atur.cabutSemuaSub": { id: "Memutus semua koneksi MCP yang menggunakan key saat ini.", en: "Disconnect all MCP connections using current keys." },
  "atur.cabutSemuaJudulModal": { id: "Cabut Semua Key?", en: "Revoke All Keys?" },
  "atur.cabutSemuaPesan": {
    id: "Apakah Anda yakin ingin mencabut semua API key yang aktif? Semua agen atau integrasi yang terhubung akan kehilangan akses saat ini juga.",
    en: "Revoke all active API keys? Every connected agent and integration loses access immediately.",
  },
  "atur.cabutSemuaYa": { id: "Ya, cabut semua", en: "Yes, revoke all" },
  "atur.cabutSemuaBtn": { id: "Cabut Semua", en: "Revoke All" },
  "atur.hapusAkunJudul": { id: "Hapus Akun & Data", en: "Delete Account & Data" },
  "atur.hapusAkunSub": { id: "Menghapus profil beserta seluruh konfigurasi secara permanen.", en: "Permanently delete the profile and all configuration." },
  "atur.hapusAkunJudulModal": { id: "Hapus Akun?", en: "Delete Account?" },
  "atur.hapusAkunPesan": {
    id: "Tindakan ini akan menghapus seluruh data proyek, log, dan pengaturan Anda secara permanen. Tindakan ini tidak dapat dibatalkan. Lanjutkan?",
    en: "This permanently deletes all project data, logs, and your settings. This cannot be undone. Continue?",
  },
  "atur.hapusAkunYa": { id: "Hapus Permanen", en: "Delete Permanently" },
  "atur.hapusAkunBtn": { id: "Hapus Akun", en: "Delete Account" },
  "atur.gagalHapusAkun": { id: "Gagal menghapus akun. Coba lagi.", en: "Failed to delete the account. Try again." },
  "atur.jaringanGagal": { id: "Jaringan gagal. Coba lagi.", en: "Network failed. Try again." },
  "atur.dangerJudul": { id: "Danger Zone", en: "Danger Zone" },
  "atur.dangerSub": { id: "Tindakan di bawah ini bersifat destruktif dan tidak dapat dibatalkan.", en: "Actions below are destructive and cannot be undone." },
  "stat.anaJudul": { id: "Produktivitas AI · 30 hari", en: "AI Productivity · 30 days" },
  "stat.anaSelesai": { id: "Tugas selesai", en: "Tasks done" },
  "stat.anaRata": { id: "Rata-rata durasi", en: "Avg duration" },
  "stat.anaMenit": { id: "{n} mnt", en: "{n} min" },
  "stat.anaError": { id: "Tingkat gagal", en: "Failure rate" },
  "stat.anaRepo": { id: "Repo tersibuk", en: "Busiest repos" },
  "stat.anaJam": { id: "Jam tersibuk (WIB)", en: "Busiest hour (WIB)" },
  "stat.anaKosong": { id: "Belum ada data 30 hari terakhir.", en: "No data in the last 30 days." },
  "stat.anaMinggu": { id: "mg {m}", en: "wk {m}" },
} as const;

export type Kunci = keyof typeof KAMUS;

export function t(lang: Lang, kunci: Kunci): string {
  return KAMUS[kunci][lang] ?? KAMUS[kunci].id;
}
